### ISSUE TITLE
SLHA Issue for the latest `request_fragment_check.py` file

### ISSUE THREAD

**Issue by DickyChant** [cms-sw/genproductions#3568]
Hi, recently EXO Is validating request which triggers an error as attached below 

```
From: PdmV Service <[pdmv.service@cern.ch](mailto:pdmv.service@cern.ch)>
Sent: Monday, November 27, 2023 4:39 PM
To: Benjamin Rand <[benjamin.rand@cern.ch](mailto:benjamin.rand@cern.ch)>; PdmV Service <[pdmv.service@cern.ch](mailto:pdmv.service@cern.ch)>
Cc: PdmV Service <[pdmv.service@cern.ch](mailto:pdmv.service@cern.ch)>
Subject: [McM] Validation failed for EXO-Run3Summer22wmLHEGS-01444
 
Hello,

Unfortunatelly EXO-Run3Summer22wmLHEGS-01444 validation failed.
Validation job exited with code 1.
Job output:

--BEGIN GEN Request checking script output--
[2023-11-27 22:21:41,096][WARNING] Using McM client without providing authentication
[2023-11-27 22:21:41,098][WARNING] Python 3.X version currently used has reached its end of life or it will reach it in the near future.
Please consider using a newer version. Python version: 3.6.8 (default, Nov 14 2023, 16:29:52) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] 

---> 1 request will be checked:
 
Current date and time: 2023-11-27 22:21:41
Prepid(s):
EXO-Run3Summer22wmLHEGS-01444
***********************************************************************************
Extension or not: 0
EXO-Run3Summer22wmLHEGS-01444    Status= new
HTo2ZdTo2mu2x_MZd-5p0_ctau-1mm_TuneCP5_13p6TeV_madgraph-pythia8
time per event (sec/event) = 12.484225434439178
Filter efficiency in the fragment =1
Cross section in the fragment =CROSS_SECTION pb
Cross section from generator parameters field = 1.0 pb

Filter efficiency in fragment =1
Filter efficiency from generator parameters field = 0.2532
CMSSW release for the request: CMSSW_12_4_16
scram_arch = el8_amd64_gcc10
PYTHIA8 version = "306-494ded5c626b685d055d5b022e918c0c"
Traceback (most recent call last):
  File "./request_fragment_check.py", line 770, in <module>
    if slha_flag == 1: gridpack_cvmfs_path, slha_all_path, slha_flag = slha_gp(gridpack_cvmfs_path,slha_flag)
  File "./request_fragment_check.py", line 119, in slha_gp
    return gridpack_cvmfs_path, slha_all_path, slha_flag
UnboundLocalError: local variable 'slha_all_path' referenced before assignment
--END GEN Request checking script output--
GEN Checking Script returned exit code 1 which means there are 1 errors
Validation WILL NOT RUN
Please correct errors in the request and run validation again


Job error stream output:

[eos-cp] copied 1/1 files and 1504 B in 0.28 seconds with 5415 B/s


Job log output:

000 (4940094.000.000) 11/27 22:21:37 Job submitted from host: <188.184.95.166:9618?addrs=188.184.95.166-9618+[2001-1458-201-e4--100-7a0]-9618&alias=[tbird02.cern.ch](http://tbird02.cern.ch/)&noUDP&sock=schedd_7053_598e>
...
040 (4940094.000.000) 11/27 22:21:40 Started transferring input files
        Transferring to host: <128.142.132.164:9618?addrs=128.142.132.164-9618+[2001-1458-301-5a--100-98]-9618&alias=[b7g12p1155.cern.ch](http://b7g12p1155.cern.ch/)&noUDP&sock=slot1_3_4311_3d48_276252>
...
040 (4940094.000.000) 11/27 22:21:40 Finished transferring input files
...
001 (4940094.000.000) 11/27 22:21:40 Job executing on host: <128.142.132.164:9618?addrs=128.142.132.164-9618+[2001-1458-301-5a--100-98]-9618&alias=[b7g12p1155.cern.ch](http://b7g12p1155.cern.ch/)&noUDP&sock=startd_3197_745e>
...
006 (4940094.000.000) 11/27 22:21:42 Image size of job updated: 13380
        0  -  MemoryUsage of job (MB)
        0  -  ResidentSetSize of job (KB)
...
040 (4940094.000.000) 11/27 22:21:42 Started transferring output files
...
040 (4940094.000.000) 11/27 22:21:42 Finished transferring output files
...
005 (4940094.000.000) 11/27 22:21:42 Job terminated.
        (1) Normal termination (return value 1)
                Usr 0 00:00:00, Sys 0 00:00:00  -  Run Remote Usage
                Usr 0 00:00:00, Sys 0 00:00:00  -  Run Local Usage
                Usr 0 00:00:00, Sys 0 00:00:00  -  Total Remote Usage
                Usr 0 00:00:00, Sys 0 00:00:00  -  Total Local Usage
        1815  -  Run Bytes Sent By Job
        20165  -  Run Bytes Received By Job
        1815  -  Total Bytes Sent By Job
        20165  -  Total Bytes Received By Job
        Partitionable Resources :    Usage  Request Allocated 
           Cpus                 :                 1         2 
           Disk (KB)            :      167       20   1646253 
           Memory (MB)          :        0        1       100 

        Job terminated of its own accord at 2023-11-27T21:21:42Z.
...


McM Announcing service
```
Tracking down, it should be from the code [here](https://github.com/cms-sw/genproductions/blob/1081bde22ae372a9bc5b0735348df808778da4f0/bin/utils/request_fragment_check.py#L101C1-L119C61):
```
def slha_gp(gridpack_cvmfs_path,slha_flag):
    if slha_flag == 1:
        if "%i" in gridpack_cvmfs_path:
            gridpack_cvmfs_path = gridpack_cvmfs_path.replace("%i","*")
        elif "%s" in gridpack_cvmfs_path:
            gridpack_cvmfs_path = gridpack_cvmfs_path.replace("%s","*")
        elif "%d" in gridpack_cvmfs_path:
            gridpack_cvmfs_path = gridpack_cvmfs_path.replace("%d","*")
        else:
            slha_flag = 0
        if slha_flag == 1:
            slha_all_path = os.path.dirname(gridpack_eos_path)
            print("Directory: "+slha_all_path)
            list_gridpack_cvmfs_path = os.listdir(slha_all_path)[0]
            print(list_gridpack_cvmfs_path)
            gridpack_cvmfs_path = slha_all_path+'/'+list_gridpack_cvmfs_path
            print("SLHA request - checking single gridpack:")
            print(gridpack_cvmfs_path)
        return gridpack_cvmfs_path, slha_all_path, slha_flag
```
In this snippet, if you look at the [first part](https://github.com/cms-sw/genproductions/blob/1081bde22ae372a9bc5b0735348df808778da4f0/bin/utils/request_fragment_check.py#L102C5-L110C26), there is a possibility to unset `slha_flag` to `0`, then the [2nd part](https://github.com/cms-sw/genproductions/blob/1081bde22ae372a9bc5b0735348df808778da4f0/bin/utils/request_fragment_check.py#L111C1-L119C1) will not be run, resulting in `slha_all_path` not `defined`.

We hope this issue can be resolved soon so that we don't have any delay for the signal request.

@tvami tagging Tamas as well

**Comment by tvami** [comment]
In this commit
https://github.com/cms-sw/genproductions/commit/e63318aa26f4b56737a592f3416ec6e949b1a84d
the block refactored and thus this issue was introduced, tagging @efeyazgan

**Comment by efeyazgan** [comment]
Thanks for reporting. Probably, more needs to be done but I just made a quick fix: https://github.com/cms-sw/genproductions/pull/3569 At least, now this request should go through w/o any problems.

**Comment by tvami** [comment]
Thanks Efe! If I may suggest, adding unit tests would be helpful for the future. For now we re-triggered validation in McM.

**Comment by efeyazgan** [comment]
Unfortunately, that's complicated for this script because of security rules.

**Comment by tvami** [comment]
Just to confirm, validation for `EXO-Run3Summer22wmLHEGS-01444` succeeded. You may close this issue.

About the unit tests, I could see ways to do this with a CI even in github w/o the actual need to access McM. Just take different kind of fragments and run the checks on those when a new PR is initiated.

**Comment by efeyazgan** [comment]
Yes, that could be done with a big set of fragments. I'll do it when find some time. Thanks.
